name: henriktudborg.dk
safe: true
lsi: false
highlighter: rouge
permalink: "/articles/:year/:month/:day/:title"
exclude: ["README.md"]
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
